FIX: Better [circle linkcheck]

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -21,6 +21,7 @@ _bash_env: &bash_env
       sudo apt install -qq graphviz optipng python3.10-venv python3-venv libxft2 ffmpeg
       python3.10 -m venv ~/python_env
       echo "set -e" >> $BASH_ENV
+      echo "set -o pipefail" >> $BASH_ENV
       echo "export OPENBLAS_NUM_THREADS=4" >> $BASH_ENV
       echo "export XDG_RUNTIME_DIR=/tmp/runtime-circleci" >> $BASH_ENV
       echo "export MNE_FULL_DATE=true" >> $BASH_ENV
