Test scheduled_updates [skip circle][skip azp]

diff --git a/.github/workflows/scheduled_updates.yml b/.github/workflows/scheduled_updates.yml
--- a/.github/workflows/scheduled_updates.yml
+++ b/.github/workflows/scheduled_updates.yml
@@ -1,6 +1,7 @@
 name: Scheduled updates
 
 on:  # yamllint disable-line rule:truthy
+  pull_request:
   schedule:
     - cron: '0 0 * * 1'  # At 00:00 every Monday
   workflow_dispatch:
@@ -61,10 +62,13 @@ jobs:
           activate-environment: true
           python-version: "3.12"
       - name: Install dependencies
-        run: pip install --upgrade packaging requests tomlkit
+        run: uv pip install -e . packaging requests tomlkit prek
       - name: Update tracked dependencies
         if: matrix.id == 'spec_zero'
         run: python ./tools/dev/spec_zero_update_versions.py
+      - name: Update pre-commit hook versions
+        if: matrix.id == 'prek_auto_update'
+        run: prek auto-update
       - name: check if files changed
         run: |
           git diff && git status --porcelain
@@ -72,24 +76,26 @@ jobs:
             echo "dirty=true" >> $GITHUB_OUTPUT
           fi
         id: status
-      - name: Create PR
-        env:
-          BRANCH: ${{ matrix.id }}
-          TITLE: ${{ matrix.title }}
-          BODY: ${{ matrix.body }}
-          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
-        run: |
-          set -xeo pipefail
-          git diff
-          git config --global user.email "50266005+mne-bot@users.noreply.github.com"
-          git config --global user.name "mne[bot]"
-          git checkout -b "$BRANCH"
-          git add -A  # doc/changes/dev/dependency.rst is a new file, the others are changed
-          git commit -m "mne[bot]: ${TITLE#MAINT: }"
-          git push origin "$BRANCH"
-          printf '%s\n\n%s\n' \
-            "Created by the \`$BRANCH\` job of this [GitHub Action run]($RUN_URL)." \
-            "$BODY" > "$RUNNER_TEMP/pr_body.md"
-          PR_NUM=$(gh pr create --base main --head "$BRANCH" --title "$TITLE" --body-file "$RUNNER_TEMP/pr_body.md")
-          echo "Opened https://github.com/mne-tools/mne-python/pull/${PR_NUM}" >> $GITHUB_STEP_SUMMARY
+      - uses: j178/prek-action@v2.0.6
         if: steps.status.outputs.dirty == 'true'
+        # - name: Create PR
+        #   env:
+        #     BRANCH: ${{ matrix.id }}
+        #     TITLE: ${{ matrix.title }}
+        #     BODY: ${{ matrix.body }}
+        #     RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+        #   run: |
+        #     set -xeo pipefail
+        #     git diff
+        #     git config --global user.email "50266005+mne-bot@users.noreply.github.com"
+        #     git config --global user.name "mne[bot]"
+        #     git checkout -b "$BRANCH"
+        #     git add -A  # doc/changes/dev/dependency.rst is a new file, the others are changed
+        #     git commit -m "mne[bot]: ${TITLE#MAINT: }"
+        #     git push origin "$BRANCH"
+        #     printf '%s\n\n%s\n' \
+        #       "Created by the \`$BRANCH\` job of this [GitHub Action run]($RUN_URL)." \
+        #       "$BODY" > "$RUNNER_TEMP/pr_body.md"
+        #     PR_NUM=$(gh pr create --base main --head "$BRANCH" --title "$TITLE" --body-file "$RUNNER_TEMP/pr_body.md")
+        #     echo "Opened https://github.com/mne-tools/mne-python/pull/${PR_NUM}" >> $GITHUB_STEP_SUMMARY
+        #   if: steps.status.outputs.dirty == 'true' && (success() || failure())
