BUG: Restore

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -69,7 +69,28 @@ jobs:
         include:
           - os: ubuntu-latest
             python: '3.13'
+            kind: pip
+          - os: ubuntu-latest
+            python: '3.13'
             kind: pip-pre
+          - os: ubuntu-latest
+            python: '3.13'
+            kind: conda
+          - os: macos-latest  # arm64 (Apple Silicon): Sequoia
+            python: '3.13'
+            kind: mamba
+          - os: macos-15-intel  # intel: Sequoia
+            python: '3.13'
+            kind: mamba
+          - os: windows-latest
+            python: '3.11'
+            kind: mamba
+          - os: ubuntu-latest
+            python: '3.12'
+            kind: minimal
+          - os: ubuntu-22.04
+            python: '3.10'
+            kind: old
     steps:
       - uses: actions/checkout@v5
         with:
@@ -102,6 +123,55 @@ jobs:
         with:
           python-version: ${{ matrix.python }}
         if: startswith(matrix.kind, 'pip')
-      - run: pip install --pre --only-binary ":all:" --extra-index-url "https://wheels.vtk.org" vtk PySide6 https://github.com/larsoner/pyvista/archive/refs/heads/main.zip
-      - run: ldd /opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/vtkmodules/vtkRenderingContext2D.cpython-313-x86_64-linux-gnu.so
-      - run: LD_DEBUG=libs python -c "from PySide6.QtWidgets import QApplication; QApplication(); import pyvista; from vtkmodules.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor; print(QVTKRenderWindowInteractor())"
+      # Python (if conda)
+      - name: Fixes for conda
+        run: |
+          # For some reason on Linux we get crashes
+          if [[ "$RUNNER_OS" == "Linux" ]]; then
+            sed -i "/numba/d" environment.yml
+          fi
+          # And on Windows and macOS PySide6.9.0 segfaults
+          if [[ "$RUNNER_OS" == "macOS" ]]; then
+            sed -i "" "s/  - PySide6 .*/  - PySide6 =6.9.2/g" environment.yml
+            sed -i "" "s/  - vtk .*/  - vtk =9.5.1/g" environment.yml
+
+          else
+            sed -i "s/  - PySide6 .*/  - PySide6 =6.9.2/g" environment.yml
+            sed -i "s/  - vtk .*/  - vtk =9.5.1/g" environment.yml
+            if [[ "$RUNNER_OS" == "Windows" ]]; then
+              echo "MNE_IS_OSMESA=true" | tee -a $GITHUB_ENV
+            fi
+          fi
+        if: matrix.kind == 'conda' || matrix.kind == 'mamba'
+      - uses: mamba-org/setup-micromamba@v2
+        with:
+          environment-file: ${{ env.CONDA_ENV }}
+          environment-name: mne
+          log-level: ${{ runner.debug == '1' && 'debug' || 'info' }}
+          create-args: >-
+            python=${{ env.PYTHON_VERSION }}
+            -v
+        if: ${{ !startswith(matrix.kind, 'pip') }}
+        timeout-minutes: 20
+      - run: bash ./tools/github_actions_dependencies.sh
+      # Minimal commands on Linux (macOS stalls)
+      - run: bash ./tools/get_minimal_commands.sh
+        if: startswith(matrix.os, 'ubuntu') && matrix.kind != 'minimal' && matrix.kind != 'old'
+      - run: bash ./tools/github_actions_infos.sh
+      # Check Qt
+      - run: bash ./tools/check_qt_import.sh $MNE_QT_BACKEND
+        if: env.MNE_QT_BACKEND != ''
+      - name: Run tests with no testing data
+        run: MNE_SKIP_TESTING_DATASET_TESTS=true pytest -m "not (ultraslowtest or pgtest)" --tb=short --cov=mne --cov-report xml -vv -rfE mne/
+        if: matrix.kind == 'minimal'
+      - run: ./tools/get_testing_version.sh
+      - uses: actions/cache@v4
+        with:
+          key: ${{ env.TESTING_VERSION }}
+          path: ~/mne_data
+      - run: bash ./tools/github_actions_download.sh
+      - run: bash ./tools/github_actions_test.sh  # for some reason on macOS we need to run "bash X" in order for a failed test run to show up
+      - uses: codecov/codecov-action@v5
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+        if: success() || failure()
